### ISSUE TITLE
create user, vendor, and admin roles

### ISSUE THREAD

**Issue by joshipaino** [easy-chef/easy-chef#10]
Please do work for this task in a branch named issue-10.

- Modify Navbar based on role of user that is currently signed in.
- Some progress have already been made from issue #5 
- User should have access to creating/editng/viewing recipes and their profiles
- Vendors should have access to adding/editing/viewing ingredients and their profiles.
- Admin should have access to both user and vendor options.

**Comment by karenwong-kw** [comment]
vendor roles added in "issue-05" branch
